[programs.localnet]
adobe = "VzRKfyFWHZtYWbQWfcnCGBrTg3tqqRV2weUqvrvVhuo"
evil = "5zAQ1XhjuHcQtUXJSTjbmyDagmKVHDMi5iADv5PfYEUK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -t 1000000 tests/"
