[programs.localnet]
adobe = "Adobe11111111111111111111111111111111111112"
evil = "5zAQ1XhjuHcQtUXJSTjbmyDagmKVHDMi5iADv5PfYEUK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
